### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by fishooo0815** [lukesmurray/markdown-anki-decks#4] opened 2021-12-04 09:06 UTC
```
mdankideck --help
Traceback (most recent call last):
  File "/usr/local/bin/mdankideck", line 5, in <module>
    from markdown_anki_decks.cli import main
  File "/usr/local/lib/python3.9/site-packages/markdown_anki_decks/cli.py", line 8, in <module>
    import genanki
  File "/usr/local/lib/python3.9/site-packages/genanki/__init__.py", line 6, in <module>
    from .model import Model
  File "/usr/local/lib/python3.9/site-packages/genanki/model.py", line 3, in <module>
    import pystache
  File "/usr/local/lib/python3.9/site-packages/pystache/__init__.py", line 2, in <module>
    from init import *
ModuleNotFoundError: No module named 'init'
```

**Comment by fishooo0815** [comment] 2021-12-04 09:07
```
mdankideck /Users/xxx/Desktop/inout /Users/xxx/Desktop/output
Traceback (most recent call last):
  File "/usr/local/bin/mdankideck", line 5, in <module>
    from markdown_anki_decks.cli import main
  File "/usr/local/lib/python3.9/site-packages/markdown_anki_decks/cli.py", line 8, in <module>
    import genanki
  File "/usr/local/lib/python3.9/site-packages/genanki/__init__.py", line 6, in <module>
    from .model import Model
  File "/usr/local/lib/python3.9/site-packages/genanki/model.py", line 3, in <module>
    import pystache
  File "/usr/local/lib/python3.9/site-packages/pystache/__init__.py", line 2, in <module>
    from init import *
ModuleNotFoundError: No module named 'init'
```

**Comment by lukesmurray** [comment] 2021-12-06 16:01
I tried to reproduce this on a fresh install of python but I wasn't able to. I would love to be able to fix this but I need some more information.

**Comment by lukesmurray** [comment] 2022-03-21 14:20
Closing for now since I was unable to reproduce and I need more info to debug. If anyone else experiences something similar please let me know and I will reopen!

**Closed as completed** 2022-03-21 14:21 UTC
Labels: needs more info
